[build]
  functions = "functions/build"
  command = "npm run build && npm run lambda-build"

[functions]
  directory = "functions/build"

[[plugins]]
  package = 'netlify-plugin-contextual-env'
  [plugins.inputs]
    mode = 'prefix'

[[headers]]
    for = "/manifest.json"
    [headers.values]
      Access-Control-Allow-Origin = "*"


