//// Web App ////

export const WEB_APP_LANDING = 'WEB_APP_LANDING';
export const WALLET_CONNECTION = 'WALLET_CONNECTION';

//// Investment Clubs ////

// CLUB_CREATE
export const CREATE_INVESTMENT_CLUB_CLICK = 'CREATE_INVESTMENT_CLUB_CLICK';
export const CREATE_ON_CHAIN_CLUB_CLICK = 'CREATE_ON_CHAIN_CLUB_CLICK';
export const RANDOMIZE_NAME_CLICK = 'RANDOMIZE_NAME_CLICK';
export const NAME_SYMBOL_NEXT_CLICK = 'NAME_SYMBOL_NEXT_CLICK';
export const DEPOSIT_TOKEN_AMOUNT_NEXT_CLICK =
  'DEPOSIT_TOKEN_AMOUNT_NEXT_CLICK';
export const DEPOSIT_WINDOW_CLICK = 'DEPOSIT_WINDOW_CLICK';
export const REVIEW_CLICK = 'REVIEW_CLICK';
export const CLUB_CREATION_DISCLAIMER_AGREE = 'CLUB_CREATION_DISCLAIMER_AGREE';
export const CONFIRM_WALLET_CLICK = 'CONFIRM_WALLET_CLICK';
export const CONTINUE_WALLET_CLICK = 'CONTINUE_WALLET_CLICK';
export const CLUB_CREATION = 'CLUB_CREATION';
export const DEPOSIT_LINK_COPY = 'DEPOSIT_LINK_COPY';
// CLUB_MANAGE
export const CLUB_MODIFY_SETTINGS_CLICK = 'CLUB_MODIFY_SETTINGS_CLICK';
export const CLUB_SUBMIT_SETTINGS = 'CLUB_SUBMIT_SETTINGS';
export const TRANSACTION_CATEGORIZE = 'TRANSACTION_CATEGORIZE';
export const TRANSACTION_NOTE_ADD = 'TRANSACTION_NOTE_ADD';
export const TRANSACTION_DETAIL_ADD = 'TRANSACTION_DETAIL_ADD';
export const ACTIVITY_CLICK = 'ACTIVITY_CLICK';
// CLUB_DEPOSIT
export const DEPOSIT_CONTINUE_CLICK = 'DEPOSIT_CONTINUE_CLICK';
export const CLUB_DEPOSIT = 'CLUB_DEPOSIT';
// CLUB_LEGAL
export const CREATE_LEGAL_ENTITY_CLICK = 'CREATE_LEGAL_ENTITY_CLICK';
export const ADMIN_PREPARE_DOCS_CLICK = 'ADMIN_PREPARE_DOCS_CLICK';
export const ADMIN_GENERATE_DOCS_CLICK = 'ADMIN_GENERATE_DOCS_CLICK';
export const ADMIN_DOCS_SIGN = 'ADMIN_DOCS_SIGN';
export const SEND_FOR_SIGNATURES_CLICK = 'SEND_FOR_SIGNATURES_CLICK';
export const SEND_FOR_SIGNATURES_LINK_COPY = 'SEND_FOR_SIGNATURES_LINK_COPY';
export const MBR_DOCS_PAGE_LANDING = 'MBR_DOCS_PAGE_LANDING';
export const MBR_GET_STARTED_CLICK = 'MBR_GET_STARTED_CLICK';
export const MBR_REVIEW_DOCS_CLICK = 'MBR_REVIEW_DOCS_CLICK';
export const MBR_DOCS_SIGN = 'MBR_DOCS_SIGN';
export const MBR_FINISH_DOCS_CLICK = 'MBR_FINISH_DOCS_CLICK';
// CLUB_DISTRIBUTE
export const MAKE_DISTRIBUTION_CLICK = 'MAKE_DISTRIBUTION_CLICK';
export const DISTRIBUTION_REVIEW_MEMBERS_CLICK =
  'DISTRIBUTION_REVIEW_MEMBERS_CLICK';
export const DISTRIBUTION_SUBMIT_CLICK = 'DISTRIBUTION_SUBMIT_CLICK';
export const DISTRIBUTION_DISCLAIMER_AGREE = 'DISTRIBUTION_DISCLAIMER_AGREE';
export const DISTRIBUTION_TRANSACTION = 'DISTRIBUTION_TRANSACTION';

//// Collectives ////

// COLLECTIVE_CREATE
export const CREATE_COLLECTIVE_CLICK = 'CREATE_COLLECTIVE_CLICK';
export const ARTWORK_UPLOAD = 'ARTWORK_UPLOAD';
export const ARTWORK_GENERATE = 'ARTWORK_GENERATE';
export const DESIGN_CONTINUE_CLICK = 'DESIGN_CONTINUE_CLICK';
export const CUSTOMIZE_CONTINUE_CLICK = 'CUSTOMIZE_CONTINUE_CLICK';
export const COLLECTIVE_CREATION_DISCLAIMER_AGREE =
  'COLLECTIVE_CREATION_DISCLAIMER_AGREE';
export const LAUNCH_CLICK = 'LAUNCH_CLICK';
export const COLLECTIVE_CREATION = 'COLLECTIVE_CREATION';
export const INVITE_LINK_COPY = 'INVITE_LINK_COPY';
export const MANAGE_DASHBOARD_CLICK = 'MANAGE_DASHBOARD_CLICK';
// COLLECTIVE_MANAGE
export const COLLECTIVE_MODIFY_SETTINGS_CLICK =
  'COLLECTIVE_MODIFY_SETTINGS_CLICK';
export const MEMBER_TOGGLE_CLICK = 'MEMBER_TOGGLE_CLICK';
export const TRANSFER_TOGGLE_CLICK = 'TRANSFER_TOGGLE_CLICK';
export const NFT_PRICE_INPUT = 'NFT_PRICE_INPUT';
export const COLLECTIVE_SUBMIT_SETTINGS = 'COLLECTIVE_SUBMIT_SETTINGS';
export const MANAGE_TRY_AGAIN_CLICK = 'MANAGE_TRY_AGAIN_CLICK';
export const SYNDICATE_CLICK = 'SYNDICATE_CLICK';
export const SNAPSHOT_CLICK = 'SNAPSHOT_CLICK';
export const GUILD_CLICK = 'GUILD_CLICK';
export const SLIK_CLICK = 'SLIK_CLICK';
export const LUMA_CLICK = 'LUMA_CLICK';
// COLLECTIVE_CLAIM
export const CLAIM_PAGE_LANDING = 'CLAIM_PAGE_LANDING';
export const JOIN_COLLECTIVE_CLICK = 'JOIN_COLLECTIVE_CLICK';
export const CLAIM_CLICK = 'CLAIM_CLICK';
export const COLLECTIVE_CLAIM_DISCLAIMER_AGREE =
  'COLLECTIVE_CLAIM_DISCLAIMER_AGREE';
export const COLLECTIVE_CLAIM = 'COLLECTIVE_CLAIM';
export const CLAIM_TRY_AGAIN_CLICK = 'CLAIM_TRY_AGAIN_CLICK';
export const VIEW_COLLECTIVE_CLICK = 'VIEW_COLLECTIVE_CLICK';

//// Uncategorized ////

export const SHARE_LINK_COPY = 'SHARE_LINK_COPY';
export const TELEGRAM_SHARE_CLICK = 'TELEGRAM_SHARE_CLICK';
export const TWITTER_SHARE_CLICK = 'TWITTER_SHARE_CLICK';
