import { initialState } from "@/redux/reducers/initialState";

// state typings
export type State = typeof initialState;

export const SET_WEB3 = "SET_WEB3";
export const UNSET_WEB3 = "UNSET_WEB3";
export const SET_LOADING = "SET_LOADING";
export const SET_PROVIDER = "SET_PROVIDER";
export const CONNECTING = "CONNECTING";
export const CONNECTED = "CONNECTED";
export const DISCONNECTED = "DISCONNECTED";
export const SHOW_WALLET_MODAL = "SHOW_WALLET_MODAL";
export const HIDE_WALLET_MODAL = "HIDE_WALLET_MODAL";
export const ADD_NEW_INVESTMENT = "ADD_NEW_INVESTMENT";
export const ALL_SYNDICATES = "ALL_SYNDICATES";
export const SHOW_ERROR_MODAL = "SHOW_ERROR_MODAL";
export const HIDE_ERROR_MODAL = "HIDE_ERROR_MODAL";
export const SET_SUBMITTING = "SET_SUBMITTING";
export const SET_SYNDICATE_DETAILS = "SET_SYNDICATE_DETAILS";
export const LOADING_SYNDICATE_DETAILS = "LOADING_SYNDICATE_DETAILS";
export const LOADING_SYNDICATE_MEMBER_DETAILS =
  "LOADING_SYNDICATE_MEMBER_DETAILS";
export const SET_MEMBER_DEPOSIT_DETAILS = "SET_MEMBER_DEPOSIT_DETAILS";
export const SET_MEMBER_WITHDRAWAL_DETAILS = "SET_MEMBER_WITHDRAWAL_DETAILS";
export const STORE_SYNDICATE_INSTANCE = "STORE_SYNDICATE_INSTANCE";
export const SYNDICATE_BY_ADDRESS = "SYNDICATE_BY_ADDRESS";
export const INVALID_SYNDICATE_ADDRESS = "INVALID_SYNDICATE_ADDRESS";
export const STORE_DEPOSIT_TOKEN_ALLOWANCE = "STORE_DEPOSIT_TOKEN_ALLOWANCE";
export const STORE_DISTRIBUTION_TOKENS_ALLOWANCES =
  "STORE_DISTRIBUTION_TOKENS_ALLOWANCES";
export const ONE_SYNDICATE_PER_ACCOUNT = "ONE_SYNDICATE_PER_ACCOUNT";
export const SET_MANAGER_FEE_ADDRESS = "SET_MANAGER_FEE_ADDRESS";
export const FOUND_SYNDICATE_ADDRESS = "FOUND_SYNDICATE_ADDRESS";
export const SET_PROVIDER_NAME = "SET_PROVIDER_NAME";
export const SET_SYNDICATE_DISTRIBUTION_TOKENS =
  "SET_SYNDICATE_DISTRIBUTION_TOKENS";

export const SET_SYNDICATE_DISTRIBUTIONS = "SET_SYNDICATE_DISTRIBUTIONS";

export const INITIALIZE_CONTRACTS = "INITIALIZE_CONTRACTS";
export const USER_LOGOUT = "USER_LOGOUT";

// manage members
export const SET_SYNDICATE_MANAGE_MEMBERS = "SET_SYNDICATE_MANAGE_MEMBERS";
export const SET_LOADING_SYNDICATE_DEPOSITOR_DETAILS =
  "SET_LOADING_SYNDICATE_DEPOSITOR_DETAILS";

// Manage actions
export const SHOW_MODIFY_MEMBER_DISTRIBUTIONS =
  "SHOW_MODIFY_MEMBER_DISTRIBUTIONS";
export const SHOW_MODIFY_CAP_TABLE = "SHOW_MODIFY_CAP_TABLE";
export const SET_SELCETED_MEMBER_ADDRESS = "SET_SELECTED_MEMBER_ADDRESS";
export const SET_SHOW_REJECT_MEMBER_DEPOSIT_OR_ADDRESS =
  "SET_SHOW_REJECT_MEMBER_DEPOSIT_OR_ADDRESS";
export const SHOW_REJECT_MEMBER_ADDRESS_ONLY =
  "SHOW_REJECT_MEMBER_ADDRESS_ONLY";
export const SHOW_REJECT_MEMBER_DEPOSIT_ONLY =
  "SHOW_REJECT_MEMBER_DEPOSIT_ONLY";
