import { CollectiveFormDesign } from '@/components/collectives/create/design';
import { CollectivesGeneratedArtwork } from '@/components/collectives/generatedArtwork';
import {
  NFTMediaType,
  NFTPreviewer
} from '@/components/collectives/nftPreviewer';
import {
  useCreateState,
  useUpdateState
} from '@/hooks/collectives/useCreateCollective';
import { FC, useEffect, useState } from 'react';
import { CreateCollectiveTitle, createHeader } from '../shared';

interface Props {
  handleNext: (e) => void;
  setNextBtnDisabled: (disabled: boolean) => void;
}

const CreateCollectiveDesign: FC<Props> = ({
  handleNext,
  setNextBtnDisabled
}) => {
  const { name, symbol, artwork, artworkUrl, artworkType, description } =
    useCreateState();
  const {
    handleNameChange,
    handleTokenSymbolChange,
    handleDescriptionChange,
    handleCancelUpload,
    handleFileUpload,
    handleCreateGeneratedArtwork,
    handleCaptureGeneratedArtwork,
    setContinueButtonActive,
    ContinueButtonActive,
    progressPercent,
    fileName,
    exceededUploadLimit
  } = useUpdateState();

  const [uploadSuccessText, setUploadSuccessText] = useState('');

  useEffect(() => {
    if (
      name.trim() &&
      (artworkUrl || artworkType === NFTMediaType.CUSTOM) &&
      description.trim() &&
      symbol &&
      !exceededUploadLimit
    ) {
      setContinueButtonActive(true);
      setNextBtnDisabled(false);
      return;
    }
    setContinueButtonActive(false);
    setNextBtnDisabled(true);
  }, [name, symbol, artworkUrl, artworkType, description, exceededUploadLimit]);

  return (
    <div>
      <CreateCollectiveTitle screen={createHeader.DESIGN} />
      <CollectiveFormDesign
        nameValue={name}
        handleNameChange={handleNameChange}
        tokenSymbolValue={symbol}
        handleTokenSymbolChange={handleTokenSymbolChange}
        descriptionValue={description}
        handleDescriptionChange={handleDescriptionChange}
        isContinueButtonActive={ContinueButtonActive}
        handleContinue={handleNext}
        handleUpload={handleFileUpload}
        uploadSuccessText={uploadSuccessText}
        uploadErrorText={exceededUploadLimit}
        handleCancelUpload={handleCancelUpload}
        progressPercentage={progressPercent}
        fileName={fileName}
        acceptFileTypes={'.png, .jpg, .jpeg, .gif, .mp4'}
        isUsingGeneratedArtwork={artworkType === NFTMediaType.CUSTOM}
        generatedArtworkBackgroundColor={artwork.backgroundColorClass}
        handleCreateGeneratedArtwork={handleCreateGeneratedArtwork}
        handleCaptureGeneratedArtwork={handleCaptureGeneratedArtwork}
      />
    </div>
  );
};

export default CreateCollectiveDesign;

export const DesignRightPanel: FC<{ customId?: string }> = ({ customId }) => {
  const { artworkType, artwork, artworkUrl, name, description, symbol } =
    useCreateState();

  const shouldUseGeneratedArtwork = artworkType === NFTMediaType.CUSTOM;

  return (
    <NFTPreviewer
      description={description}
      loading={{
        description: description === '',
        name: name === '',
        artwork: artworkUrl === ''
      }}
      mediaSource={
        shouldUseGeneratedArtwork ? (
          <CollectivesGeneratedArtwork
            label={name}
            backgroundColorClass={artwork.backgroundColorClass}
            isForDisplay={true}
            customId={customId}
          />
        ) : (
          artworkUrl
        )
      }
      showAutoGeneratedArtDisclaimer={true}
      mediaType={artworkType}
      name={name}
      symbol={'✺' + symbol}
      customClasses={'w-full'}
    />
  );
};
