/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { IERC20Contract } from "./IERC20";
import { ISyndicateClosedEndFundAllowlistLogicV0Contract } from "./ISyndicateClosedEndFundAllowlistLogicV0";
import { ISyndicateClosedEndFundDepositLogicV0Contract } from "./ISyndicateClosedEndFundDepositLogicV0";
import { ISyndicateClosedEndFundDepositTransferLogicV0Contract } from "./ISyndicateClosedEndFundDepositTransferLogicV0";
import { ISyndicateClosedEndFundDistributionLogicV0Contract } from "./ISyndicateClosedEndFundDistributionLogicV0";
import { ISyndicateClosedEndFundGetterLogicV0Contract } from "./ISyndicateClosedEndFundGetterLogicV0";
import { ISyndicateClosedEndFundManagerLogicV0Contract } from "./ISyndicateClosedEndFundManagerLogicV0";
import { ISyndicateClosedEndFundProxyV0Contract } from "./ISyndicateClosedEndFundProxyV0";
import { ISyndicateClosedEndFundStoreGettersV0Contract } from "./ISyndicateClosedEndFundStoreGettersV0";
import { ISyndicateClosedEndFundStoreSettersV0Contract } from "./ISyndicateClosedEndFundStoreSettersV0";
import { ISyndicateClosedEndFundStoreV0Contract } from "./ISyndicateClosedEndFundStoreV0";
import { ISyndicateIntegrationsCoordinatorLogicV0Contract } from "./ISyndicateIntegrationsCoordinatorLogicV0";
import { MigrationsContract } from "./Migrations";
import { OwnableContract } from "./Ownable";
import { SyndicateClosedEndFundAllowlistLogicV0Contract } from "./SyndicateClosedEndFundAllowlistLogicV0";
import { SyndicateClosedEndFundDepositLogicV0Contract } from "./SyndicateClosedEndFundDepositLogicV0";
import { SyndicateClosedEndFundDepositTransferLogicV0Contract } from "./SyndicateClosedEndFundDepositTransferLogicV0";
import { SyndicateClosedEndFundDistributionLogicV0Contract } from "./SyndicateClosedEndFundDistributionLogicV0";
import { SyndicateClosedEndFundGetterLogicV0Contract } from "./SyndicateClosedEndFundGetterLogicV0";
import { SyndicateClosedEndFundLogicContract } from "./SyndicateClosedEndFundLogic";
import { SyndicateClosedEndFundManagerLogicV0Contract } from "./SyndicateClosedEndFundManagerLogicV0";
import { SyndicateClosedEndFundProxyV0Contract } from "./SyndicateClosedEndFundProxyV0";
import { SyndicateClosedEndFundStoreV0Contract } from "./SyndicateClosedEndFundStoreV0";
import { SyndicateIntegrationsCoordinatorLogicV0Contract } from "./SyndicateIntegrationsCoordinatorLogicV0";
import { SyndicateOwnerLogicContract } from "./SyndicateOwnerLogic";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "IERC20"): IERC20Contract;
      require(
        name: "ISyndicateClosedEndFundAllowlistLogicV0"
      ): ISyndicateClosedEndFundAllowlistLogicV0Contract;
      require(
        name: "ISyndicateClosedEndFundDepositLogicV0"
      ): ISyndicateClosedEndFundDepositLogicV0Contract;
      require(
        name: "ISyndicateClosedEndFundDepositTransferLogicV0"
      ): ISyndicateClosedEndFundDepositTransferLogicV0Contract;
      require(
        name: "ISyndicateClosedEndFundDistributionLogicV0"
      ): ISyndicateClosedEndFundDistributionLogicV0Contract;
      require(
        name: "ISyndicateClosedEndFundGetterLogicV0"
      ): ISyndicateClosedEndFundGetterLogicV0Contract;
      require(
        name: "ISyndicateClosedEndFundManagerLogicV0"
      ): ISyndicateClosedEndFundManagerLogicV0Contract;
      require(
        name: "ISyndicateClosedEndFundProxyV0"
      ): ISyndicateClosedEndFundProxyV0Contract;
      require(
        name: "ISyndicateClosedEndFundStoreGettersV0"
      ): ISyndicateClosedEndFundStoreGettersV0Contract;
      require(
        name: "ISyndicateClosedEndFundStoreSettersV0"
      ): ISyndicateClosedEndFundStoreSettersV0Contract;
      require(
        name: "ISyndicateClosedEndFundStoreV0"
      ): ISyndicateClosedEndFundStoreV0Contract;
      require(
        name: "ISyndicateIntegrationsCoordinatorLogicV0"
      ): ISyndicateIntegrationsCoordinatorLogicV0Contract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
      require(
        name: "SyndicateClosedEndFundAllowlistLogicV0"
      ): SyndicateClosedEndFundAllowlistLogicV0Contract;
      require(
        name: "SyndicateClosedEndFundDepositLogicV0"
      ): SyndicateClosedEndFundDepositLogicV0Contract;
      require(
        name: "SyndicateClosedEndFundDepositTransferLogicV0"
      ): SyndicateClosedEndFundDepositTransferLogicV0Contract;
      require(
        name: "SyndicateClosedEndFundDistributionLogicV0"
      ): SyndicateClosedEndFundDistributionLogicV0Contract;
      require(
        name: "SyndicateClosedEndFundGetterLogicV0"
      ): SyndicateClosedEndFundGetterLogicV0Contract;
      require(
        name: "SyndicateClosedEndFundLogic"
      ): SyndicateClosedEndFundLogicContract;
      require(
        name: "SyndicateClosedEndFundManagerLogicV0"
      ): SyndicateClosedEndFundManagerLogicV0Contract;
      require(
        name: "SyndicateClosedEndFundProxyV0"
      ): SyndicateClosedEndFundProxyV0Contract;
      require(
        name: "SyndicateClosedEndFundStoreV0"
      ): SyndicateClosedEndFundStoreV0Contract;
      require(
        name: "SyndicateIntegrationsCoordinatorLogicV0"
      ): SyndicateIntegrationsCoordinatorLogicV0Contract;
      require(name: "SyndicateOwnerLogic"): SyndicateOwnerLogicContract;
    }
  }
}

export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  ISyndicateClosedEndFundAllowlistLogicV0Contract,
  ISyndicateClosedEndFundAllowlistLogicV0Instance,
} from "./ISyndicateClosedEndFundAllowlistLogicV0";
export {
  ISyndicateClosedEndFundDepositLogicV0Contract,
  ISyndicateClosedEndFundDepositLogicV0Instance,
} from "./ISyndicateClosedEndFundDepositLogicV0";
export {
  ISyndicateClosedEndFundDepositTransferLogicV0Contract,
  ISyndicateClosedEndFundDepositTransferLogicV0Instance,
} from "./ISyndicateClosedEndFundDepositTransferLogicV0";
export {
  ISyndicateClosedEndFundDistributionLogicV0Contract,
  ISyndicateClosedEndFundDistributionLogicV0Instance,
} from "./ISyndicateClosedEndFundDistributionLogicV0";
export {
  ISyndicateClosedEndFundGetterLogicV0Contract,
  ISyndicateClosedEndFundGetterLogicV0Instance,
} from "./ISyndicateClosedEndFundGetterLogicV0";
export {
  ISyndicateClosedEndFundManagerLogicV0Contract,
  ISyndicateClosedEndFundManagerLogicV0Instance,
} from "./ISyndicateClosedEndFundManagerLogicV0";
export {
  ISyndicateClosedEndFundProxyV0Contract,
  ISyndicateClosedEndFundProxyV0Instance,
} from "./ISyndicateClosedEndFundProxyV0";
export {
  ISyndicateClosedEndFundStoreGettersV0Contract,
  ISyndicateClosedEndFundStoreGettersV0Instance,
} from "./ISyndicateClosedEndFundStoreGettersV0";
export {
  ISyndicateClosedEndFundStoreSettersV0Contract,
  ISyndicateClosedEndFundStoreSettersV0Instance,
} from "./ISyndicateClosedEndFundStoreSettersV0";
export {
  ISyndicateClosedEndFundStoreV0Contract,
  ISyndicateClosedEndFundStoreV0Instance,
} from "./ISyndicateClosedEndFundStoreV0";
export {
  ISyndicateIntegrationsCoordinatorLogicV0Contract,
  ISyndicateIntegrationsCoordinatorLogicV0Instance,
} from "./ISyndicateIntegrationsCoordinatorLogicV0";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { OwnableContract, OwnableInstance } from "./Ownable";
export {
  SyndicateClosedEndFundAllowlistLogicV0Contract,
  SyndicateClosedEndFundAllowlistLogicV0Instance,
} from "./SyndicateClosedEndFundAllowlistLogicV0";
export {
  SyndicateClosedEndFundDepositLogicV0Contract,
  SyndicateClosedEndFundDepositLogicV0Instance,
} from "./SyndicateClosedEndFundDepositLogicV0";
export {
  SyndicateClosedEndFundDepositTransferLogicV0Contract,
  SyndicateClosedEndFundDepositTransferLogicV0Instance,
} from "./SyndicateClosedEndFundDepositTransferLogicV0";
export {
  SyndicateClosedEndFundDistributionLogicV0Contract,
  SyndicateClosedEndFundDistributionLogicV0Instance,
} from "./SyndicateClosedEndFundDistributionLogicV0";
export {
  SyndicateClosedEndFundGetterLogicV0Contract,
  SyndicateClosedEndFundGetterLogicV0Instance,
} from "./SyndicateClosedEndFundGetterLogicV0";
export {
  SyndicateClosedEndFundLogicContract,
  SyndicateClosedEndFundLogicInstance,
} from "./SyndicateClosedEndFundLogic";
export {
  SyndicateClosedEndFundManagerLogicV0Contract,
  SyndicateClosedEndFundManagerLogicV0Instance,
} from "./SyndicateClosedEndFundManagerLogicV0";
export {
  SyndicateClosedEndFundProxyV0Contract,
  SyndicateClosedEndFundProxyV0Instance,
} from "./SyndicateClosedEndFundProxyV0";
export {
  SyndicateClosedEndFundStoreV0Contract,
  SyndicateClosedEndFundStoreV0Instance,
} from "./SyndicateClosedEndFundStoreV0";
export {
  SyndicateIntegrationsCoordinatorLogicV0Contract,
  SyndicateIntegrationsCoordinatorLogicV0Instance,
} from "./SyndicateIntegrationsCoordinatorLogicV0";
export {
  SyndicateOwnerLogicContract,
  SyndicateOwnerLogicInstance,
} from "./SyndicateOwnerLogic";
